### ISSUE TITLE
Font Mastering

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/glory#2]
**Diacritics**
- [x] Composite glyphs need to be made out of components using anchors
- [x] Comb.case are missing
- [x] Misaligned diacritics
- [x] Create caron.alt and adjust Lcaron, lcaron, dcaron, tcaron

**Glyphs & Outlines**
- [x] Missing glyphs: 0x00B5 (MICRO SIGN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH) 
- [x] Superior forms balanced
- [ ] Add extreme points
- [ ] Correct outlines direction

**OT Features**
- [ ] Ensure OT features include everything and are working well (e.g. fi fl included)

![Screen Shot 2021-03-19 at 06 54 29](https://user-images.githubusercontent.com/48698976/111776768-6a90d480-8880-11eb-88d3-f5730738cba7.png)

![Screen Shot 2021-03-19 at 07 00 12](https://user-images.githubusercontent.com/48698976/111777058-c5c2c700-8880-11eb-9a97-5a82a65fd946.png)

**Level 2 improvements**
- [ ] Round shapes overshoot differ
- [ ] Spacing review and fixes
- [ ] Kerning review and fixes + kerning groups missing

**Comment by crystaltype** [comment]
> **Diacritics**
> 
> * [x]  Composite glyphs need to be made out of components using anchors
> * [x]  Comb.case are missing
> * [x]  Misaligned diacritics
> * [x]  Create caron.alt and adjust Lcaron, lcaron, dcaron, tcaron
> 
> **Glyphs & Outlines**
> 
> * [x]  Missing glyphs: 0x00B5 (MICRO SIGN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)
> * [x]  Superior forms balanced
> * [ ]  Add extreme points
> * [ ]  Correct outlines direction
> 
> **OT Features**
> 
> * [ ]  Ensure OT features include everything and are working well (e.g. fi fl included)
> 
> ![Screen Shot 2021-03-19 at 06 54 29](https://user-images.githubusercontent.com/48698976/111776768-6a90d480-8880-11eb-88d3-f5730738cba7.png)
> 
> ![Screen Shot 2021-03-19 at 07 00 12](https://user-images.githubusercontent.com/48698976/111777058-c5c2c700-8880-11eb-9a97-5a82a65fd946.png)
> 
> **Level 2 improvements**
> 
> * [ ]  Round shapes overshoot differ
> * [ ]  Spacing review and fixes
> * [ ]  Kerning review and fixes + kerning groups missing

**Comment by crystaltype** [comment]
- Adding extreme points lead to (a lot of) incompatible glyphs

**Comment by vv-monsalve** [comment]
> * Adding extreme points lead to (a lot of) incompatible glyphs

Inspecting at the file now, I get that due to its curved stems plus rounded corners it would add some extremes that probably would create some issues.

However, what I see now is that although they are reported as "compatible" now, the nodes differ in any case so the interpolation doesn't run smoothly.

I would say it should be fixed in L1, but this would need @davelab6 confirmation.

**Thin Master**
![Screen Shot 2021-04-12 at 12 49 35](https://user-images.githubusercontent.com/48698976/114438667-acfeb600-9b8d-11eb-8018-9938f029ad58.png)
**ExtraBold Master**
![Screen Shot 2021-04-12 at 12 50 00](https://user-images.githubusercontent.com/48698976/114438692-b4be5a80-9b8d-11eb-92fe-d09fe1541a23.png)
**Interpolation result**
![Glory-Interpolation](https://user-images.githubusercontent.com/48698976/114440964-6a8aa880-9b90-11eb-98af-f089294a87c4.gif)

**Comment by davelab6** [comment]
I recommend to convert cubic to quadratic and handle the smooth interpolation of the rounded corners much better that way.

**Comment by davelab6** [comment]
@eliheuer may be interested to chat with you both about this topic

**Comment by vv-monsalve** [comment]
> I recommend to convert cubic to quadratic and handle the smooth interpolation of the rounded corners much better that way.

quadratic paths are harder to administrate (at least to me, I'm not really familiar with them)

> @eliheuer may be interested to chat with you both about this topic

Ok. I'll consult this with him. 

However, @davelab6, confirming before jumping into something that could take long now (as this should be fixed for the entire font, not only A) do we address this in L1 or later?

**Comment by davelab6** [comment]
> this should be fixed for the entire font, not only A

You can do it only for A, within GlyphsApp, I think, since v2.5 

https://glyphsapp.com/news/new-features-in-glyphs-2-5

> do we address this in L1 or later?

The interpolation shown in that GIF is unacceptable to publish

**Comment by davelab6** [comment]
> quadratic paths are harder to administrate (at least to me, I'm not really familiar with them)

Well yes, except for when dealing with smooth curve to sharp point transitions in interpolation, and then cubics don't work at all and quadratics work very nicely :)

**Comment by vv-monsalve** [comment]
> You can do it only for A, within GlyphsApp, I think, since v2.5

I mean we would need to check the interpolation works well for the entire font.

> The interpolation shown in that GIF is unacceptable to publish

I agree.

> Well yes, except for when dealing with smooth curve to sharp point transitions in interpolation, and then cubics don't work at all and quadratics work very nicely :)

Ok, we shall learn ;-)

**Comment by eliheuer** [comment]
When I did the variable font upgrade for [Orbitron](https://fonts.google.com/specimen/Orbitron) I needed to interpolate between sharp and round corners. So I redrew the whole font in quadratic curves using Glyphs. I'm happy to answer any questions about that process. If it would be helpful to anyone, I could even try redrawing some glyphs from this typeface in quadratic and making a pull request back to the project, just to get that process started.

Take a look at these images to get a better idea of how this was handled with [Orbitron](https://github.com/eliheuer/orbitron-vf).

![quadratic-variation-example](https://user-images.githubusercontent.com/5162664/115287198-d5922d00-a104-11eb-8286-d7ec0aada833.gif)

<img width="739" alt="orbitron-quad-demo" src="https://user-images.githubusercontent.com/5162664/115287490-302b8900-a105-11eb-97e5-4fca4ae61abd.png">

**Comment by vv-monsalve** [comment]
Thank you Eli! The images are really explanatory. @crystaltype will give this a try and we'll tell know if we would need any help further, maybe in a video call.

**Comment by crystaltype** [comment]
@eliheuer thanks a lot for the guidelines.
I've some experiences drawing with quadratic curves in the past when I was still working with FontCreator.

But as far as I know, glyphs doesn't support drawing directly using quadratic curves, could you please tell me more about the tools or plugin needed to draw using quadratic curves using glyphs?

**Comment by eliheuer** [comment]
I just worked around the parts of Glyphs that don't support Quadratic curves. This way of working was difficult and required some time and patience. There aren't any tools or plugins that I know of.

Any progress on this @schriftgestalt ? This issue shows I'm not the only person who would like this feature.

**Comment by schriftgestalt** [comment]
What parts didn't work in Glyphs?

**Comment by eliheuer** [comment]
Working with points when a font uses quadratic curves, things like adding off-curve points...
This is the source file from the images above: https://github.com/eliheuer/orbitron-vf/blob/master/sources/Orbitron-Roman.glyphs

Thanks!

**Comment by eliheuer** [comment]
Working with stuff like this is difficult, it's not clear how to add new off-curve points, but I just tested it now in Glyphs3 and the knife tool seems to work!

Source: https://github.com/eliheuer/orbitron-vf/blob/master/sources/Orbitron-Roman.glyphs
<img width="967" alt="glyphs-quad-screenshot" src="https://user-images.githubusercontent.com/5162664/119059269-d678e180-b984-11eb-90b4-946df9211a6f.png">

**Comment by schriftgestalt** [comment]
That problem did come up in the Forum a while back. https://forum.glyphsapp.com/t/tt-curve-editing/15012/4

Next time, ask on the forum when you miss a feature ;)

**Comment by eliheuer** [comment]
Thank you! Will do.
