### ISSUE TITLE
Linear interpolation + backwards compatibility

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/glory#3]
Currently, the font has 6 weights: Thin, Light, Regular, Medium, Bold, ExtraBold with linear interpolation thus the weight steps between them are not quite balanced.

The weight values could be tweaked to improve the interpolation steps as well as to anticipate the intermediate weights as they would be included by the API anyway, but Glory is already published in [MyFonts](https://www.myfonts.com/fonts/typesetit/glory?tab=familyPackages), so this would leave the GF version incompatible with the current instances in the market. 

@davelab6 could we go ahead or would that be an issue?

**Current interpolation**
Thin, Light, Regular, Medium, Bold, ExtraBold
![Screen Shot 2021-03-19 at 07 29 00](https://user-images.githubusercontent.com/48698976/111779991-cd846a80-8884-11eb-926c-c6d5972b38b1.png)

**Possible interpolation**
Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold
![Screen Shot 2021-03-19 at 07 22 57](https://user-images.githubusercontent.com/48698976/111779490-31f2fa00-8884-11eb-8c97-63a09f1bfddc.png)

**Comment by vv-monsalve** [comment]
PS. Also, the current linear interpolation is returning a lack of `avar` table. The Interpolation fixes would solve that too.

**Comment by davelab6** [comment]
Please go ahead, we don't need compatibility with the legacy retail fonts

**Comment by davelab6** [comment]
> Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold

I don't think the wght-min is a "true" 100 Thin weight, I think 200 ExtraLight is more appropriate. 

The wght-max is good as 800.

**Comment by vv-monsalve** [comment]
> Please go ahead, we don't need compatibility with the legacy retail fonts

Good, thanks. I'll keep this in mind for further projects

**Comment by vv-monsalve** [comment]
> t think the wght-min is a "true" 100 Thin weight, I think 200 ExtraLight is more appropriate.

OK, good. Now with the green light about non-compatibility with the legacy retail fonts, I'll inspect all the schema again.
